markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "Data Geek"
markdown: kramdown

author: "Norris"
atom-baseurl: "http://norris-niu.top"
disqus: "Norris New"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Notes
    class: fa fa-book
    href: /book/index.html 
  - title: Tools
    class: fa fa-wrench
    href: /tool.html
  # - title: Subscribe
  #   class: fa fa-rss
  #   href: /atom.xml

